### ISSUE TITLE
Invalid Expo config plugin in v4.3.0

### ISSUE THREAD

**Issue by KimmoHernborg** [auth0/react-native-auth0#1081]
### Checklist

- [x] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [x] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [x] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When running `expo install react-native-auth0` or `expo prebuild` I get the following error message:

```
CommandError: Package "react-native-auth0" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'typeof'
```
Cannot create a working build with version 4.3.0, but earlier versions work.

### Reproduction

1. Install version v4.3.0 (latest at the time of writing) into project `expo install react-native-auth0`
```
CommandError: Package "react-native-auth0" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'typeof'
```
2. Prebuild to update native folders `expo prebuild`
```
CommandError: Package "react-native-auth0" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Unexpected token 'typeof'
```
3. Trying to run either a `expo run:ios` or `expo run:android` fails with the following error:
```
The following build commands failed:
        PhaseScriptExecution [CP-User]\ Generate\ app.config\ for\ prebuilt\ Constants.manifest /path/00LoginExpo-dpxholqrmdwopgdlraqemjiyijwe/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/EXConstants.build/Script-46EB2E00016BE0.sh (in target 'EXConstants' from project 'Pods')
        Building workspace 00LoginExpo with scheme 00LoginExpo and configuration Debug
```

### Additional context

Tested and recreated in an updated **00-Login-Expo** project (updated to newer version of Expo)

### react-native-auth0 version

v4.3.0

### React Native version

0.74.5

### Expo version

51.0.39

### Platform

iOS

### Platform version(s)

18.2

**Comment by andyconchubhair** [comment]
I encountered the same issue with 4.4.0 using react native 0.73.6. Installing 4.2.0 works

**Comment by irinagastmaier** [comment]
Any updates on this issue? I’m experiencing the same problem with versions 4.3 and 4.4. The only version that works for me is 4.2 on Expo 51 with React Native 0.74.5.

**Comment by poovamraj** [comment]
Hey folks, we are looking into this. We will get back ASAP, sorry on the inconvenience

**Comment by subhankarmaiti** [comment]
I've dug into the issue and it appears the problem is related to the version of Expo CLI. As noted in the [Expo changelog](https://github.com/expo/expo/blob/main/packages/expo/CHANGELOG.md), recent updates have resolved this problem. Instead of using a locally installed Expo CLI, please try using the latest version via npx. For example, you can run:
```
npx expo prebuild
```
This command ensures you’re using the most up-to-date Expo CLI, which should address the issue reported here. Let me know if you run into any further problems!

**Comment by Dakuan** [comment]
not working for me either locally or on my EAS builds...

**Comment by subhankarmaiti** [comment]
Interesting, @Dakuan can you share the output of
```
npx expo -v
```

**Comment by Dakuan** [comment]
`0.18.31`

and EAS:

```
yarn run v1.22.21
$ /Users/expo/workingdir/build/node_modules/.bin/expo prebuild --no-install --platform ios
The ios project is malformed, project files will be cleared and reinitialized.
- Clearing ios
✔ Cleared ios code
CommandError: Package "react-native-auth0" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin
Cannot use import statement outside a module
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn expo prebuild --no-install --platform ios exited with non-zero code: 1
```

**Comment by subhankarmaiti** [comment]
@Dakuan seems like you are using the old version of expo cli. You should use the latest version `0.22.18` to execute the command.

**Comment by KimmoHernborg** [comment]
> [@Dakuan](https://github.com/Dakuan) seems like you are using the old version of expo cli. You should use the latest version `0.22.18`.

The version of the Expo CLI is connected to the version of Expo you are using in the project. My project is using Expo version 51.0.39 and the Expo CLI version 0.18.31. You need to support earlier version of Expo CLI, not everyone can be on the latest version of Expo, and it is not feasible to upgrade the project just to get the latest version of Expo CLi.

**Comment by Robspin** [comment]
Using the latest expo CLI and EAS fixed it for me.

**Comment by poovamraj** [comment]
@Dakuan, as @Robspin mentioned you can try the latest version of EAS CLI - `15.0.12`

**Comment by poovamraj** [comment]
@KimmoHernborg you are right, Expo since 46 uses "Local Expo CLI" but as mentioned in their announcement - https://blog.expo.dev/the-new-expo-cli-f4250d8e3421 and there they also mention

> This does mean if you need a CLI bug fix, you’ll either need to update your expo package version or force the CLI version with Yarn resolutions in the package.json:

```
{
  "resolutions": {
    "@expo/cli": "xxx" 
  }
}
```

Hope this helps.

**Comment by subhankarmaiti** [comment]
This issue is resolved in the latest version `4.6.0`.

**Comment by lkp-k** [comment]
I still get this issue, on latest v5.3.1

<img width="555" height="163" alt="Image" src="https://github.com/user-attachments/assets/19cd15d2-282a-49d2-abfd-5ee496f5c995" />

**Comment by sagar-0208** [comment]
> I still get this issue, on latest v5.3.1
> 
> <img alt="Image" width="555" height="163" src="https://private-user-images.githubusercontent.com/104889168/529867174-19cd15d2-282a-49d2-abfd-5ee496f5c995.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY1ODIwMjAsIm5iZiI6MTc2NjU4MTcyMCwicGF0aCI6Ii8xMDQ4ODkxNjgvNTI5ODY3MTc0LTE5Y2QxNWQyLTI4MmEtNDlkMi1hYmZkLTVlZTQ5NmY1Yzk5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNFQxMzA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjY4OGE2MmI0YjBlYzRhNDViMmJiMDhlYzY5YzkxNDEyN2YwYTQ3YzI4ZTYyMzQ3NjM5ZmM4NjRlNjRlMmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ov1jh1zD4rjIIcTLFpzujl7gmnfvcXi8cILVMy9aGwQ">

Same issue here. This might be the reason why my app crashes every time I try to test it via TestFlight. Does anyone have a fix or workaround for this? @subhankarmaiti
