### ISSUE TITLE
clearSession not work

### ISSUE THREAD

**Issue by zhulichaoZW** [auth0/react-native-auth0#209]
clearSession can not logout, and not enter the success callback or error callback, no console execute.
```
auth0.webAuth.clearSession({federated: true}).then(() => console.log('success')).catch(() => console.log('error'));
```

**Comment by ananova** [comment]
I've been trying to find a solution for this for a while as well.

I am presented with:

![image](https://user-images.githubusercontent.com/6103816/53141954-d7700c80-35dd-11e9-8483-bea34a86e081.png)

If I click cancel, I then get an error.

![image](https://user-images.githubusercontent.com/6103816/53142043-2cac1e00-35de-11e9-9c29-c77c461dc9af.png)

**Comment by cocojoe** [comment]
Ah yes I see, in this case the operation was successful. However, the browser didn't close.
Can you try adding your *Callback URL* to the *Allowed Logout URLs* section of your application in the [Auth0 Dashboard](https://manage.auth0.com/#/)

**Comment by reedyrm** [comment]
@zhulichaoZW I had a similiar problem where I was calling clearSession({}), I was able to fix the issue by adding the clientId as part of the parameters to clearSession

```clearSession({clientId: "...."})```

**Comment by delanoyejonathan** [comment]
Hey, this seems to be a regression in v1.4.0. I had the same problem when implementing it in my application, just a blank screen with "ok" displayed on it when trying to execute clearSession() on iOS.

I tried @cocojoe 's and @reedyrm  's possible solutions, but neither of those worked in my case.

I was able to fix this issue in my application by going back to the previous version (v1.3.1).

**Comment by jhltom** [comment]
I have the same problem and tried all @cocojoe 's @reedyrm 's and @delanoyejonathan 's solutions but none of them work for me.  I also tried logging and seems like clearSession() is not returning anything, since the second log below is not returning anything. I'd appreciate some help!

```
_onLogout = () => {
    console.log("This one logs")
      auth0.webAuth
        .clearSession({})
        .then(success => {
          console.log("This one does not")
          this.setState({ accessToken: null });
        })
        .catch(error => console.log(error));
  };

```

**Comment by wprk** [comment]
I had the same issue, tried combinations of all the above solutions and reverting to v1.3.1 was the only thing that worked for me. Thanks @delanoyejonathan

**Comment by alexpyoung** [comment]
It might also be worth noting that the consent dialog appears before the web view @ananova showed 

<img width="324" alt="Screen Shot 2019-04-17 at 7 24 14 PM" src="https://user-images.githubusercontent.com/2624187/56327098-d0c9c580-6146-11e9-9e32-4d03184d2fb2.png">

I was also able to resolve this issue by reverting to v1.3.1, where the alert is not presented

**Comment by winseyli** [comment]
@alexpyoung thanks for finding this. We are implementing this today and were not happy with the consent dialog. It happens on v1.4.0 but not v1.3.1
Not sure if this dialog will happen in all future releases after v1.4 ...?

**Comment by factsfinder** [comment]
Implementing both @reedyrm and @cocojoe solutions fixed the issue in my case.

**Comment by BoKKeR** [comment]
I fixed this using all the tips in this thread (even downgrade). Something to note:

`Note that if the clientID parameter is included, the returnTo URL that is provided must be listed in the Application's Allowed Logout URLs in the Auth0 dashboard. However, if the clientID parameter is not included, the returnTo URL must be listed in the Allowed Logout URLs at the account level in the Auth0 dashboard.`

**Comment by lbalmaceda** [comment]
The iOS redirection is fixed in the release `1.5.0`. If this continue to happen, please re-open.

**Comment by drewdecarme** [comment]
I'm still getting this "error" in `2.3.0`. Exact same issue as above, where there isn't a promise being returned as well as the "Sign in" dialog.

**Comment by fsolis17** [comment]
I am seeing the sign in dialog when logging out in 2.6.0. Should this be reopened or should a new issue be created?

**Comment by digitalIntrospection** [comment]
We're using 2.13.3 and it still seems to fail with iOS
