### ISSUE TITLE
React native 0.69.0 support

### ISSUE THREAD

**Issue by Bardiamist** [auth0/react-native-auth0#486]
I can't sync Project with Graddle in React native 0.69.0

Repro step
1. `npx react-native init diff`
1. `yarn add react-native-auth0`
1. Open with Android Studio

<details>
<summary>Output</summary>

```
Build file '/Users/bardiamist/Documents/files/diff/node_modules/react-native-auth0/android/build.gradle' line: 95

A problem occurred configuring project ':react-native-auth0'.
> Could not resolve all files for configuration ':react-native-auth0:implementation'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-auth0
      > Cannot choose between the following variants of com.facebook.react:react-native:0.69.0:
          - debugVariantDefaultRuntimePublication
          - releaseVariantDefaultRuntimePublication
        All of them match the consumer attributes:
          - Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-native:0.69.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'debug' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'aar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-native:0.69.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'release' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'aar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

...

```

</details>

**Comment by marc-wittwer** [comment]
+1 :)

**Comment by lutzk** [comment]
its not working for ios either
when creating a fresh rn app with v 0.69
and running `pod install`
the pods of this lib are not added to the podfile.lock
and manual linking is removed in rn 069

**Comment by poovamraj** [comment]
@Bardiamist we are looking into this issue, Can you help us by providing the following information.
Is it localized to RN version 69?
Can you provide us a minimal sample application in which the issue is reproducing?

**Comment by Bardiamist** [comment]
>Is it localized to RN version 69?

Yes

>Can you provide us a minimal sample application in which the issue is reproducing?

It's simple to create a new
But if you need, it's here: https://github.com/Bardiamist/diff/tree/auth0

**Comment by poovamraj** [comment]
Looks like commenting out [line 95](https://github.com/auth0/react-native-auth0/blob/master/android/build.gradle#L95) seems to make it work. Still exploring what change in the new React version is causing this. You can check this fix locally and let us know your feedback. We will explore more details before rolling out the fix.

**Comment by poovamraj** [comment]
Hey @Bardiamist, we have released a new version here - https://github.com/auth0/react-native-auth0/pull/489 to fix this issue. Please check this out and let us know. We are closing this issue for now but please feel free to reopen it for further doubts

**Comment by Bardiamist** [comment]
Sync Project with Graddle passed
Not sure about build, now blocked with another depencdency

**Comment by lucasff** [comment]
The build is still broken for me on React Native 0.70.6, on a freshly created project using CRNA, adding `react-native-auth0` triggers 

`> Task :react-native-auth0:androidJavadoc FAILED`

**Comment by Monsy99** [comment]
Same story as in @lucasff  post. I am using:
```    "react-native": "^0.70.5",
    "react-native-auth0": "^2.16.0", ```
